### ISSUE TITLE
whether the model could take arbitrary resolution rgb and depth as input when reasoning

### ISSUE THREAD

**Issue by z1V-Chan** [DepthAnything/PromptDA#2]
interesting work. however, it seems that this model could not take 848x480 images as the input during reasoning. the following error came out.

```
Traceback (most recent call last):
  File "/ssd3/czw/PromptDA/demo,py", line 11, in <module>
    depth = model.predict(image, prompt_depth) # HxW, depth in meters
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/czw/miniconda3/envs/DA-prompt/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ssd3/czw/PromptDA/promptda/promptda.py", line 103, in predict
    return self.forward(image, prompt_depth)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd3/czw/PromptDA/promptda/promptda.py", line 91, in forward
    features = self.pretrained.get_intermediate_layers(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd3/czw/PromptDA/torchhub/facebookresearch_dinov2_main/vision_transformer.py", line 308, in get_intermediate_layers
    outputs = self._get_intermediate_layers_not_chunked(x, n)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd3/czw/PromptDA/torchhub/facebookresearch_dinov2_main/vision_transformer.py", line 272, in _get_intermediate_layers_not_chunked
    x = self.prepare_tokens_with_masks(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd3/czw/PromptDA/torchhub/facebookresearch_dinov2_main/vision_transformer.py", line 214, in prepare_tokens_with_masks
    x = self.patch_embed(x)
        ^^^^^^^^^^^^^^^^^^^
  File "/home/czw/miniconda3/envs/DA-prompt/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd3/czw/PromptDA/torchhub/facebookresearch_dinov2_main/dinov2/layers/patch_embed.py", line 73, in forward
    assert H % patch_H == 0, f"Input image height {H} is not a multiple of patch height {patch_H}"
           ^^^^^^^^^^^^^^^^
AssertionError: Input image height 480 is not a multiple of patch height 14
```

i wonder what shapes are possible to enter since the paper shows this model could handle 3024×4032 rgb and 240×320 depth images. i appreciate any suggestions.

**Comment by z1V-Chan** [comment]
The problem is solved by resizing the width and height of the image into integer multiples of patch size
